/* Stock Oclean X Ultra 20 UI layout tables: picture offsets, elements, descriptors and
 * screen lists. Generated by re/tools/extract_ui_tables.py from the stock ota.bin.
 * Layout only -- the pictures themselves stay in the brush's resource partition. */
#pragma once
#include <stdint.h>

/* picture offsets in the type 0x40 / subtype 0x00 data partition (stock rodata 0x3c11b248) */
#define STOCK_PIC_COUNT 927
static const uint32_t STOCK_PIC_OFF[STOCK_PIC_COUNT] = {
  0x000000, 0x001810, 0x003020, 0x004830, 0x006040, 0x007850, 0x009060, 0x00a870,
  0x00c080, 0x010540, 0x014a00, 0x018ec0, 0x01f2c0, 0x0256c0, 0x02bac0, 0x031ec0,
  0x0382c0, 0x03e6c0, 0x044ac0, 0x049c00, 0x04ed40, 0x053e80, 0x058fc0, 0x05e100,
  0x064500, 0x06a860, 0x070bc0, 0x070c80, 0x070d40, 0x070e00, 0x070ec0, 0x070f80,
  0x071040, 0x071100, 0x0711c0, 0x071280, 0x071340, 0x071400, 0x0714c0, 0x075520,
  0x0755e0, 0x0756a0, 0x075760, 0x075820, 0x0758e0, 0x0759a0, 0x075a60, 0x075b20,
  0x075be0, 0x075ca0, 0x075d60, 0x075e20, 0x079e80, 0x079f40, 0x07a000, 0x07a0c0,
  0x07a180, 0x07a240, 0x07a300, 0x07a3c0, 0x07a480, 0x07a540, 0x07a600, 0x07a6c0,
  0x07a780, 0x07e7e0, 0x07e8a0, 0x07e960, 0x07ea20, 0x07eae0, 0x07eba0, 0x07ec60,
  0x07ed20, 0x07ede0, 0x07eea0, 0x07ef60, 0x07f020, 0x07f0e0, 0x083140, 0x083200,
  0x0832c0, 0x083380, 0x083440, 0x083500, 0x0835c0, 0x083680, 0x083740, 0x083800,
  0x0838c0, 0x083980, 0x083a40, 0x087a00, 0x087ac0, 0x087b80, 0x087c40, 0x087d00,
  0x087dc0, 0x087e80, 0x087f40, 0x088000, 0x0880c0, 0x088180, 0x088240, 0x088300,
  0x08c360, 0x08c420, 0x08c4e0, 0x08c5a0, 0x08c660, 0x08c720, 0x08c7e0, 0x08c8a0,
  0x08c960, 0x08ca20, 0x08cae0, 0x08cba0, 0x08cc60, 0x08cd20, 0x08cde0, 0x08cea0,
  0x08cf60, 0x08d020, 0x08d0e0, 0x08d1a0, 0x08d260, 0x08d320, 0x08d3e0, 0x08d4a0,
  0x08d560, 0x08d5ec, 0x08d6c4, 0x08d84c, 0x08d8c4, 0x08da4c, 0x08dbd4, 0x08dcbe,
  0x08dda8, 0x08de92, 0x08df7c, 0x08e066, 0x08e150, 0x08e228, 0x08e300, 0x08e3ea,
  0x08e4d4, 0x08e570, 0x08e674, 0x08e75e, 0x08e848, 0x08e932, 0x08ea1c, 0x08eb06,
  0x08ebf0, 0x08ecda, 0x08edc4, 0x08eeae, 0x08ef98, 0x08f082, 0x08f2da, 0x08f55a,
  0x08f7da, 0x09315a, 0x096ada, 0x09a45a, 0x09ddda, 0x0a175a, 0x0a50da, 0x0a8a5a,
  0x0ac3da, 0x0afd5a, 0x0b36da, 0x0b705a, 0x0ba9da, 0x0bac7a, 0x0baf1a, 0x0bb1ba,
  0x0bb45a, 0x0bb6fa, 0x0bb99a, 0x0bbc3a, 0x0bbeda, 0x0bc17a, 0x0bc41a, 0x0bc6ba,
  0x0bc84a, 0x0bcad4, 0x0bcd74, 0x0bd014, 0x0bd2b4, 0x0bd554, 0x0bd7f4, 0x0bda94,
  0x0bdd34, 0x0bdfd4, 0x0be274, 0x0be514, 0x0be7b4, 0x0bea54, 0x0becf4, 0x0bef94,
  0x0bf234, 0x0bf4d4, 0x0bf774, 0x0bfa14, 0x0bfcb4, 0x0bff54, 0x0c0a4c, 0x0c1544,
  0x0c203c, 0x0c61dc, 0x0c681c, 0x0c6e5c, 0x0c749c, 0x0c7adc, 0x0c811c, 0x0c875c,
  0x0c8d9c, 0x0c93dc, 0x0c9a1c, 0x0ca05c, 0x0ca69c, 0x0cacdc, 0x0cb31c, 0x0cb95c,
  0x0cbf9c, 0x0cc5dc, 0x0cd124, 0x0d3524, 0x0d9924, 0x0dfd24, 0x0e6124, 0x0ec524,
  0x0f2924, 0x0f8d24, 0x0ff124, 0x105524, 0x10b924, 0x111d24, 0x118124, 0x11e524,
  0x124924, 0x12ad24, 0x131124, 0x137524, 0x13d924, 0x143d24, 0x14a124, 0x14c2e4,
  0x14e4a4, 0x150664, 0x152824, 0x1549e4, 0x156ba4, 0x158d64, 0x15af24, 0x15d0e4,
  0x15f2a4, 0x161464, 0x163624, 0x1657e4, 0x1679a4, 0x169b64, 0x16bd24, 0x16dee4,
  0x1700a4, 0x172264, 0x174424, 0x1765e4, 0x1787a4, 0x17a964, 0x17cb24, 0x17ece4,
  0x180ea4, 0x183064, 0x185224, 0x1873e4, 0x1895a4, 0x18b764, 0x18d924, 0x18fae4,
  0x191ca4, 0x193e64, 0x196024, 0x1981e4, 0x19a3a4, 0x19c564, 0x19e724, 0x1a08e4,
  0x1a2aa4, 0x1a4c64, 0x1a6e24, 0x1a8fe4, 0x1ab1a4, 0x1ad364, 0x1af524, 0x1b16e4,
  0x1b38a4, 0x1b5a64, 0x1b66e4, 0x1b7364, 0x1b7fe4, 0x1b8c64, 0x1b98e4, 0x1ba564,
  0x1bb1e4, 0x1bbe64, 0x1bcae4, 0x1bd764, 0x1be3e4, 0x1bf064, 0x1bfce4, 0x1c0964,
  0x1c15e4, 0x1c2264, 0x1c2ee4, 0x1c4564, 0x1c5be4, 0x1c7264, 0x1c88e4, 0x1c9f64,
  0x1cb5e4, 0x1ccc64, 0x1ce2e4, 0x1cf964, 0x1d0fe4, 0x1d2664, 0x1d3ce4, 0x1d5364,
  0x1d69e4, 0x1d8064, 0x1d96e4, 0x1dad64, 0x1dcf24, 0x1df0e4, 0x1e12a4, 0x1e3464,
  0x1e5624, 0x1e77e4, 0x1e99a4, 0x1ebb64, 0x1edd24, 0x1efee4, 0x1f20a4, 0x1f4264,
  0x1f6424, 0x1f85e4, 0x1fa7a4, 0x1fc964, 0x1feb24, 0x200ce4, 0x202ea4, 0x205064,
  0x207224, 0x2093e4, 0x20b5a4, 0x20d764, 0x20f924, 0x211ae4, 0x213ca4, 0x215e64,
  0x218024, 0x21a1e4, 0x21c3a4, 0x21e564, 0x220724, 0x2228e4, 0x224aa4, 0x226c64,
  0x228e24, 0x22afe4, 0x22d1a4, 0x22f364, 0x231524, 0x2336e4, 0x2358a4, 0x237a64,
  0x239c24, 0x23bde4, 0x23dfa4, 0x240164, 0x242324, 0x2444e4, 0x2466a4, 0x248864,
  0x24aa24, 0x24cbe4, 0x24eda4, 0x250f64, 0x253124, 0x2552e4, 0x2574a4, 0x259664,
  0x25b824, 0x25d9e4, 0x25fba4, 0x261d64, 0x263f24, 0x2660e4, 0x2682a4, 0x26a464,
  0x26c624, 0x26e7e4, 0x2709a4, 0x272b64, 0x274d24, 0x276ee4, 0x2790a4, 0x27b264,
  0x27d424, 0x27f5e4, 0x2817a4, 0x283964, 0x285b24, 0x287ce4, 0x289ea4, 0x28c064,
  0x28e224, 0x2903e4, 0x2925a4, 0x294764, 0x296924, 0x298ae4, 0x29aca4, 0x29ce64,
  0x29f024, 0x2a11e4, 0x2a33a4, 0x2a5564, 0x2a7724, 0x2a98e4, 0x2abaa4, 0x2adc64,
  0x2afe24, 0x2b1fe4, 0x2b41a4, 0x2b6364, 0x2b8524, 0x2ba6e4, 0x2bc8a4, 0x2bea64,
  0x2c0c24, 0x2c2de4, 0x2c4fa4, 0x2c7164, 0x2c9324, 0x2cb4e4, 0x2cd6a4, 0x2cf864,
  0x2d1a24, 0x2d3be4, 0x2d5da4, 0x2d7f64, 0x2da124, 0x2dc2e4, 0x2de4a4, 0x2e0704,
  0x2e28c4, 0x2e4a84, 0x2e6c44, 0x2e8e04, 0x2eafc4, 0x2ed184, 0x2ef344, 0x2f1504,
  0x2f36c4, 0x2f5884, 0x2f7a44, 0x2f9c04, 0x2fbdc4, 0x2fdf84, 0x300144, 0x302304,
  0x3044c4, 0x306684, 0x308844, 0x30aa04, 0x30cbc4, 0x30ed84, 0x310f44, 0x313104,
  0x3152c4, 0x317484, 0x319644, 0x31b804, 0x31d9c4, 0x31fb84, 0x321d44, 0x323f04,
  0x3260c4, 0x328284, 0x32a444, 0x32c604, 0x32e7c4, 0x330984, 0x332b44, 0x334d04,
  0x336ec4, 0x339084, 0x33b244, 0x33d404, 0x33f5c4, 0x341784, 0x343944, 0x345b04,
  0x347cc4, 0x349e84, 0x34c044, 0x34e204, 0x3503c4, 0x352584, 0x354744, 0x356904,
  0x358ac4, 0x35ac84, 0x35ce44, 0x35f004, 0x3611c4, 0x363384, 0x365544, 0x367704,
  0x3698c4, 0x36ba84, 0x36dc44, 0x36fe04, 0x371fc4, 0x374184, 0x376344, 0x378504,
  0x37a6c4, 0x37c884, 0x37ea44, 0x380c04, 0x382dc4, 0x384f84, 0x387144, 0x389304,
  0x38b4c4, 0x38d684, 0x38f844, 0x391a04, 0x393bc4, 0x395d84, 0x397f44, 0x39a104,
  0x39c2c4, 0x39e484, 0x3a0644, 0x3a2804, 0x3a49c4, 0x3a6b84, 0x3a8d44, 0x3aaf04,
  0x3ad0c4, 0x3ad704, 0x3add44, 0x3ae384, 0x3ae9c4, 0x3af004, 0x3af644, 0x3afc84,
  0x3b02c4, 0x3b0904, 0x3b0f44, 0x3b1584, 0x3b1bc4, 0x3b2204, 0x3b2844, 0x3b2e84,
  0x3b34c4, 0x3b3b04, 0x3b4144, 0x3b4784, 0x3b4dc4, 0x3b61c4, 0x3b68cc, 0x3b6f0c,
  0x3b71ac, 0x3b78b4, 0x3bdcb4, 0x3c40b4, 0x3ca4b4, 0x3d08b4, 0x3d6cb4, 0x3dd0b4,
  0x3e34b4, 0x3e98b4, 0x3efcb4, 0x3f60b4, 0x3fc4b4, 0x4028b4, 0x408cb4, 0x40f0b4,
  0x4154b4, 0x417674, 0x419834, 0x41b9f4, 0x41dbb4, 0x41fd74, 0x421f34, 0x4240f4,
  0x4262b4, 0x428474, 0x42a634, 0x42c7f4, 0x42e9b4, 0x430b74, 0x432d34, 0x434ef4,
  0x4370b4, 0x439274, 0x43b434, 0x43d5f4, 0x43f7b4, 0x441974, 0x443b34, 0x445cf4,
  0x447eb4, 0x44a074, 0x44c234, 0x44e3f4, 0x4505b4, 0x452774, 0x454934, 0x456af4,
  0x458cb4, 0x45ae74, 0x45d034, 0x45f1f4, 0x4613b4, 0x463574, 0x465734, 0x4678f4,
  0x469ab4, 0x46bc74, 0x46de34, 0x46fff4, 0x4721b4, 0x474374, 0x476534, 0x4786f4,
  0x47a8b4, 0x47ca74, 0x47ec34, 0x480df4, 0x4871f4, 0x48d5f4, 0x4939f4, 0x499df4,
  0x49a754, 0x49d954, 0x49edf4, 0x49f934, 0x4a03d4, 0x4a0d34, 0x4a11b4, 0x4a15b4,
  0x4a1dd4, 0x4a3314, 0x4a3d14, 0x4a4fd4, 0x4a6294, 0x4a7554, 0x4a9354, 0x4aa114,
  0x4aaed4, 0x4abc94, 0x4aca54, 0x4ad814, 0x4ae5d4, 0x4af394, 0x4b0154, 0x4b0f14,
  0x4b1cd4, 0x4b2a94, 0x4b3854, 0x4b4614, 0x4b53d4, 0x4b6194, 0x4b6f54, 0x4b7d14,
  0x4ba514, 0x4bcd14, 0x4bf514, 0x4c1e54, 0x4c4654, 0x4c6e54, 0x4c9794, 0x4cbf94,
  0x4ce794, 0x4d1034, 0x4d3834, 0x4d60d4, 0x4d8a14, 0x4db494, 0x4ddc94, 0x4e0494,
  0x4e2dd4, 0x4e2ef4, 0x4e3014, 0x4e3134, 0x4e3254, 0x4e3374, 0x4e3494, 0x4e35b4,
  0x4e36d4, 0x4e37f4, 0x4e3914, 0x4e3a34, 0x4e3ac4, 0x4e3e8c, 0x4e4254, 0x4e5b54,
  0x4e6e14, 0x4ed214, 0x4f3614, 0x4f9a14, 0x4fbbd4, 0x4fdd94, 0x4fff54, 0x502114,
  0x5042d4, 0x506494, 0x508654, 0x50a814, 0x50c9d4, 0x50eb94, 0x510d54, 0x512f14,
  0x5150d4, 0x517294, 0x519454, 0x51b614, 0x51d7d4, 0x51db9c, 0x51df64, 0x51e04e,
  0x51f686, 0x520cbe, 0x5222f6, 0x52392e, 0x524f66, 0x52659e, 0x527bd6, 0x52920e,
  0x52a846, 0x52be7e, 0x52d4b6, 0x52eaee, 0x530126, 0x53175e, 0x532d96, 0x5343ce,
  0x535a06, 0x53703e, 0x538676, 0x539cae, 0x53b2e6, 0x53c91e, 0x53e53e, 0x53e5fe,
  0x53e6be, 0x53e77e, 0x53e83e, 0x53e8fe, 0x53e9be, 0x53ea7e, 0x53eb3e, 0x53ebfe,
  0x53ecbe, 0x53ed7e, 0x53ee3e, 0x542e9e, 0x54505e, 0x54721e, 0x5493de, 0x54b59e,
  0x54d75e, 0x54f91e, 0x551ade, 0x553c9e, 0x555e5e, 0x55801e, 0x55a1de, 0x55c39e,
  0x55e55e, 0x56071e, 0x5628de, 0x564a9e, 0x566c5e, 0x567c9e, 0x568cde, 0x569d1e,
  0x56ad5e, 0x56bd9e, 0x56cdde, 0x56de1e, 0x56ee5e, 0x56fe9e, 0x570ede, 0x571f1e,
  0x572f5e, 0x573f9e, 0x574fde, 0x57601e, 0x57705e, 0x57809e, 0x5790de, 0x57a11e,
  0x57b15e, 0x57c19e, 0x57d1de, 0x57e21e, 0x57f25e, 0x58029e, 0x5812de, 0x58231e,
  0x58335e, 0x58439e, 0x5853de, 0x58641e, 0x58745e, 0x58849e, 0x5894de, 0x58a51e,
  0x58b55e, 0x58e75e, 0x59195e, 0x594b5e, 0x597d5e, 0x59af5e, 0x59e15e, 0x5a135e,
  0x5a455e, 0x5a775e, 0x5aa95e, 0x5adb5e, 0x5b0d5e, 0x5b3f5e, 0x5b715e, 0x5ba35e,
  0x5bd55e, 0x5c075e, 0x5c395e, 0x5c3d26, 0x5c3ed6, 0x5c4026, 0x5c41d6, 0x5c4e56,
  0x5c5ad6, 0x5c6756, 0x5c9956, 0x5ccb56, 0x5cfd56, 0x5d2f56, 0x5d6156, 0x5d9356,
  0x5dc556, 0x5df756, 0x5e2956, 0x5e5b56, 0x5e8d56, 0x5ebf56, 0x5ef156, 0x5f2356,
  0x5f2596, 0x5f27d6, 0x5f2a16, 0x5f2c56, 0x5f2e96, 0x5f30d6, 0x5f3316, 0x5f3556,
  0x5f3796, 0x5f39d6, 0x5f3ac6, 0x5f8de6, 0x5fe106, 0x603426, 0x608746, 0x60da66,
  0x612d86, 0x6180a6, 0x61d3c6, 0x6226e6, 0x627a06, 0x62cd26, 0x632046, 0x637366,
  0x63c686, 0x642446, 0x648206, 0x64dfc6, 0x653d86, 0x659b46, 0x65f906, 0x6656c6,
  0x66b486, 0x671246, 0x677006, 0x67cdc6, 0x682b86, 0x688946, 0x68e706, 0x6944c6,
  0x69a286, 0x6a0046, 0x6a5e06, 0x6abbc6, 0x6b1986, 0x6b4cc6, 0x6b7d86, 0x6bae46,
  0x6bdf06, 0x6c0fc6, 0x6c4086, 0x6c7146, 0x6ca206, 0x6cd2c6, 0x6d0386, 0x6d3446,
  0x6d6506, 0x6d95c6, 0x6dc686, 0x6df746, 0x6e2806, 0x6e58c6, 0x6e8986,
};

/* ids 927..950: offset = 0x77e000 + STOCK_ZONE_OFF[id-927]; 44 rows x 240 B (80 px x {b0,b1,alpha}) (stock rodata 0x3c11b1e8) */
static const uint32_t STOCK_ZONE_OFF[24] = {0x0, 0x2940, 0x5280, 0x7bc0, 0xa500, 0xce40, 0xf780, 0x120c0, 0x14a00, 0x17340, 0x19c80, 0x1c5c0, 0x1ef00, 0x21840, 0x24180, 0x26ac0, 0x29400, 0x2bd40, 0x2e680, 0x30fc0, 0x33900, 0x36240, 0x38b80, 0x3b4c0};

/* descriptors ("*C#" + id + variant in stock RAM): the variant byte is the dynamic part.
 * DS_<stock address> = index. */
enum {
  DS_3fc9c023 = 0,
  DS_3fc9c029 = 1,
  DS_3fc9c02f = 2,
  DS_3fc9c035 = 3,
  DS_3fc9c03b = 4,
  DS_3fc9c041 = 5,
  DS_3fc9c047 = 6,
  DS_3fc9c04d = 7,
  DS_3fc9c053 = 8,
  DS_3fc9c059 = 9,
  DS_3fc9c05f = 10,
  DS_3fc9c065 = 11,
  DS_3fc9c06b = 12,
  DS_3fc9c071 = 13,
  DS_3fc9c077 = 14,
  DS_3fc9c07d = 15,
  DS_3fc9c083 = 16,
  DS_3fc9c089 = 17,
  DS_3fc9c08f = 18,
  DS_3fc9c095 = 19,
  DS_3fc9c09b = 20,
  DS_3fc9c0a1 = 21,
  DS_3fc9c0a7 = 22,
  DS_3fc9c0ad = 23,
  DS_3fc9c0b3 = 24,
  DS_3fc9c0b9 = 25,
  DS_3fc9c0bf = 26,
  DS_3fc9c0c5 = 27,
  DS_3fc9c0cb = 28,
  DS_3fc9c0d1 = 29,
  DS_3fc9c0d7 = 30,
  DS_3fc9c0dd = 31,
  DS_3fc9c0e3 = 32,
  DS_3fc9c0e9 = 33,
  DS_3fc9c0ef = 34,
  DS_3fc9c0f5 = 35,
  DS_3fc9c0fb = 36,
  DS_3fc9c101 = 37,
  DS_3fc9c107 = 38,
  DS_3fc9c10d = 39,
  DS_3fc9c113 = 40,
  DS_3fc9c119 = 41,
  DS_3fc9c11f = 42,
  DS_3fc9c125 = 43,
  DS_3fc9c12b = 44,
  DS_3fc9c131 = 45,
  DS_3fc9c137 = 46,
  DS_3fc9c13d = 47,
  DS_3fc9c143 = 48,
  DS_3fc9c149 = 49,
  DS_3fc9c14f = 50,
  DS_3fc9c155 = 51,
  DS_3fc9c15b = 52,
  DS_3fc9c161 = 53,
  DS_3fc9c167 = 54,
  DS_3fc9c16d = 55,
  DS_3fc9c173 = 56,
  DS_3fc9c179 = 57,
  DS_3fc9c17f = 58,
  DS_3fc9c185 = 59,
  DS_3fc9c18b = 60,
  DS_3fc9c191 = 61,
  DS_3fc9c197 = 62,
  DS_3fc9c19d = 63,
  DS_3fc9c1a3 = 64,
  DS_3fc9c1a9 = 65,
  DS_3fc9c1af = 66,
  DS_3fc9c1b5 = 67,
  DS_3fc9c1bb = 68,
  DS_3fc9c1c1 = 69,
  DS_3fc9c1c7 = 70,
  DS_3fc9c1cd = 71,
  DS_3fc9c1d3 = 72,
  DS_3fc9c1d9 = 73,
  DS_3fc9c1df = 74,
  DS_3fc9c1e5 = 75,
  DS_3fc9c1eb = 76,
  DS_3fc9c1f1 = 77,
  DS_3fc9c1f7 = 78,
  DS_3fc9c1fd = 79,
  DS_3fc9c203 = 80,
  DS_3fc9c209 = 81,
  DS_3fc9c20f = 82,
  DS_3fc9c215 = 83,
  DS_3fc9c21b = 84,
  DS_3fc9c221 = 85,
  DS_3fc9c227 = 86,
  DS_3fc9c22d = 87,
  DS_3fc9c233 = 88,
  DS_3fc9c239 = 89,
  DS_3fc9c23f = 90,
  DS_3fc9c245 = 91,
  DS_3fc9c24b = 92,
  DS_3fc9c251 = 93,
  DS_3fc9c257 = 94,
  DS_3fc9c25d = 95,
  DS_3fc9c263 = 96,
  DS_3fc9c269 = 97,
  DS_3fc9c26f = 98,
  DS_3fc9c275 = 99,
  DS_3fc9c27b = 100,
  DS_3fc9c281 = 101,
  DS_3fc9c287 = 102,
  DS_3fc9c28d = 103,
  DS_3fc9c293 = 104,
  DS_3fc9c299 = 105,
  DS_3fc9c29f = 106,
  DS_3fc9c2a5 = 107,
  DS_3fc9c2ab = 108,
  DS_3fc9c2b1 = 109,
  DS_3fc9c2b7 = 110,
  DS_3fc9c2bd = 111,
  DS_3fc9c2c3 = 112,
  DS_3fc9c2c9 = 113,
  DS_3fc9c2cf = 114,
  DS_3fc9c2d5 = 115,
  DS_3fc9c2db = 116,
  DS_3fc9c2e1 = 117,
  DS_3fc9c2e7 = 118,
  DS_3fc9c2ed = 119,
  DS_3fc9c2f3 = 120,
  DS_3fc9c2f9 = 121,
  DS_3fc9c2ff = 122,
  DS_3fc9c305 = 123,
  DS_3fc9c30b = 124,
  DS_3fc9c311 = 125,
  DS_3fc9c317 = 126,
  DS_3fc9c31d = 127,
  DS_3fc9c323 = 128,
  DS_3fc9c329 = 129,
  DS_3fc9c32f = 130,
  DS_3fc9c335 = 131,
  DS_3fc9c33b = 132,
  DS_3fc9c341 = 133,
  DS_3fc9c347 = 134,
  DS_3fc9c353 = 135,
  DS_3fc9c359 = 136,
  DS_3fc9c35f = 137,
  DS_3fc9c365 = 138,
  DS_3fc9c36b = 139,
  DS_3fc9c371 = 140,
  DS_3fc9c377 = 141,
  DS_3fc9c37d = 142,
  DS_3fc9c383 = 143,
  DS_3fc9c389 = 144,
  DS_3fc9c38f = 145,
  DS_3fc9c395 = 146,
  DS_3fc9c39b = 147,
  DS_3fc9c3a1 = 148,
  DS_3fc9c3a7 = 149,
  DS_3fc9c3ad = 150,
  DS_3fc9c3b3 = 151,
  DS_3fc9c3b9 = 152,
  DS_3fc9c3bf = 153,
  DS_3fc9c3c5 = 154,
  DS_3fc9c3d1 = 155,
  DS_3fc9c3d7 = 156,
  DS_3fc9c3dd = 157,
  DS_3fc9c3e3 = 158,
  DS_3fc9c3e9 = 159,
  DS_3fc9c3ef = 160,
  DS_3fc9c3f5 = 161,
  DS_3fc9c3fb = 162,
  DS_3fc9c401 = 163,
  DS_3fc9c407 = 164,
  DS_3fc9c40d = 165,
  DS_3fc9c413 = 166,
  DS_3fc9c419 = 167,
  DS_3fc9c41f = 168,
  DS_3fc9c42b = 169,
  DS_3fc9c437 = 170,
  DS_3fc9c43d = 171,
  DS_3fc9c449 = 172,
  DS_3fc9c44f = 173,
  DS_3fc9c455 = 174,
  DS_3fc9c45b = 175,
  DS_3fc9c461 = 176,
  DS_3fc9c467 = 177,
  DS_3fc9c46d = 178,
  DS_3fc9c473 = 179,
  DS_3fc9c479 = 180,
  STOCK_DESC_COUNT = 181
};
typedef struct { uint16_t base_id; uint8_t var0; } stock_desc_t;
static const stock_desc_t STOCK_DESCS[STOCK_DESC_COUNT] = {
  { 850,   0}, /* [  0] desc@0x3fc9c023 */
  { 225,   0}, /* [  1] desc@0x3fc9c029 */
  { 843,   0}, /* [  2] desc@0x3fc9c02f */
  { 843,   0}, /* [  3] desc@0x3fc9c035 */
  { 843,   0}, /* [  4] desc@0x3fc9c03b */
  { 843,   0}, /* [  5] desc@0x3fc9c041 */
  { 843,   0}, /* [  6] desc@0x3fc9c047 */
  { 843,   0}, /* [  7] desc@0x3fc9c04d */
  { 843,   0}, /* [  8] desc@0x3fc9c053 */
  { 843,   0}, /* [  9] desc@0x3fc9c059 */
  { 843,   0}, /* [ 10] desc@0x3fc9c05f */
  { 843,   0}, /* [ 11] desc@0x3fc9c065 */
  { 843,   0}, /* [ 12] desc@0x3fc9c06b */
  { 843,   0}, /* [ 13] desc@0x3fc9c071 */
  { 843,   0}, /* [ 14] desc@0x3fc9c077 */
  { 843,   0}, /* [ 15] desc@0x3fc9c07d */
  { 843,   0}, /* [ 16] desc@0x3fc9c083 */
  { 843,   0}, /* [ 17] desc@0x3fc9c089 */
  { 173,   0}, /* [ 18] desc@0x3fc9c08f */
  { 173,   0}, /* [ 19] desc@0x3fc9c095 */
  { 172,   0}, /* [ 20] desc@0x3fc9c09b */
  { 173,   0}, /* [ 21] desc@0x3fc9c0a1 */
  { 173,   0}, /* [ 22] desc@0x3fc9c0a7 */
  { 129,   0}, /* [ 23] desc@0x3fc9c0ad */
  { 129,   0}, /* [ 24] desc@0x3fc9c0b3 */
  { 129,   0}, /* [ 25] desc@0x3fc9c0b9 */
  { 118,   0}, /* [ 26] desc@0x3fc9c0bf */
  { 118,   0}, /* [ 27] desc@0x3fc9c0c5 */
  { 118,   0}, /* [ 28] desc@0x3fc9c0cb */
  { 118,   0}, /* [ 29] desc@0x3fc9c0d1 */
  { 118,   0}, /* [ 30] desc@0x3fc9c0d7 */
  { 118,   0}, /* [ 31] desc@0x3fc9c0dd */
  { 118,   0}, /* [ 32] desc@0x3fc9c0e3 */
  { 696,   0}, /* [ 33] desc@0x3fc9c0e9 */
  { 697,   0}, /* [ 34] desc@0x3fc9c0ef */
  { 697,   0}, /* [ 35] desc@0x3fc9c0f5 */
  { 697,   0}, /* [ 36] desc@0x3fc9c0fb */
  { 697,   0}, /* [ 37] desc@0x3fc9c101 */
  { 707,   0}, /* [ 38] desc@0x3fc9c107 */
  { 707,   0}, /* [ 39] desc@0x3fc9c10d */
  { 707,   0}, /* [ 40] desc@0x3fc9c113 */
  { 707,   0}, /* [ 41] desc@0x3fc9c119 */
  { 707,   0}, /* [ 42] desc@0x3fc9c11f */
  { 707,   0}, /* [ 43] desc@0x3fc9c125 */
  { 697,   0}, /* [ 44] desc@0x3fc9c12b */
  { 697,   0}, /* [ 45] desc@0x3fc9c131 */
  { 697,   0}, /* [ 46] desc@0x3fc9c137 */
  { 697,   0}, /* [ 47] desc@0x3fc9c13d */
  { 654,   0}, /* [ 48] desc@0x3fc9c143 */
  { 654,   0}, /* [ 49] desc@0x3fc9c149 */
  { 654,   0}, /* [ 50] desc@0x3fc9c14f */
  { 654,   0}, /* [ 51] desc@0x3fc9c155 */
  { 653,   0}, /* [ 52] desc@0x3fc9c15b */
  { 653,   0}, /* [ 53] desc@0x3fc9c161 */
  { 653,   0}, /* [ 54] desc@0x3fc9c167 */
  { 653,   0}, /* [ 55] desc@0x3fc9c16d */
  { 195,   0}, /* [ 56] desc@0x3fc9c173 */
  { 195,   0}, /* [ 57] desc@0x3fc9c179 */
  { 185,   0}, /* [ 58] desc@0x3fc9c17f */
  { 185,   0}, /* [ 59] desc@0x3fc9c185 */
  { 172,   0}, /* [ 60] desc@0x3fc9c18b */
  { 173,   0}, /* [ 61] desc@0x3fc9c191 */
  { 172,   0}, /* [ 62] desc@0x3fc9c197 */
  { 173,   0}, /* [ 63] desc@0x3fc9c19d */
  { 173,   0}, /* [ 64] desc@0x3fc9c1a3 */
  { 172,   0}, /* [ 65] desc@0x3fc9c1a9 */
  { 173,   0}, /* [ 66] desc@0x3fc9c1af */
  { 173,   0}, /* [ 67] desc@0x3fc9c1b5 */
  { 173,   0}, /* [ 68] desc@0x3fc9c1bb */
  { 173,   0}, /* [ 69] desc@0x3fc9c1c1 */
  { 173,   0}, /* [ 70] desc@0x3fc9c1c7 */
  { 173,   0}, /* [ 71] desc@0x3fc9c1cd */
  { 173,   0}, /* [ 72] desc@0x3fc9c1d3 */
  { 173,   0}, /* [ 73] desc@0x3fc9c1d9 */
  { 173,   0}, /* [ 74] desc@0x3fc9c1df */
  { 173,   0}, /* [ 75] desc@0x3fc9c1e5 */
  { 998,   0}, /* [ 76] desc@0x3fc9c1eb */
  { 949,   0}, /* [ 77] desc@0x3fc9c1f1 */
  { 947,   0}, /* [ 78] desc@0x3fc9c1f7 */
  { 945,   0}, /* [ 79] desc@0x3fc9c1fd */
  { 943,   0}, /* [ 80] desc@0x3fc9c203 */
  { 941,   0}, /* [ 81] desc@0x3fc9c209 */
  { 939,   0}, /* [ 82] desc@0x3fc9c20f */
  { 937,   0}, /* [ 83] desc@0x3fc9c215 */
  { 935,   0}, /* [ 84] desc@0x3fc9c21b */
  { 933,   0}, /* [ 85] desc@0x3fc9c221 */
  { 931,   0}, /* [ 86] desc@0x3fc9c227 */
  { 929,   0}, /* [ 87] desc@0x3fc9c22d */
  { 927,   0}, /* [ 88] desc@0x3fc9c233 */
  { 926,   0}, /* [ 89] desc@0x3fc9c239 */
  { 909,   0}, /* [ 90] desc@0x3fc9c23f */
  { 908,   0}, /* [ 91] desc@0x3fc9c245 */
  { 888,   0}, /* [ 92] desc@0x3fc9c24b */
  { 874,   0}, /* [ 93] desc@0x3fc9c251 */
  { 862,   0}, /* [ 94] desc@0x3fc9c257 */
  { 861,   0}, /* [ 95] desc@0x3fc9c25d */
  { 860,   0}, /* [ 96] desc@0x3fc9c263 */
  { 859,   0}, /* [ 97] desc@0x3fc9c269 */
  { 858,   0}, /* [ 98] desc@0x3fc9c26f */
  { 857,   0}, /* [ 99] desc@0x3fc9c275 */
  { 856,   0}, /* [100] desc@0x3fc9c27b */
  { 850,   0}, /* [101] desc@0x3fc9c281 */
  { 849,   0}, /* [102] desc@0x3fc9c287 */
  { 848,   0}, /* [103] desc@0x3fc9c28d */
  { 847,   0}, /* [104] desc@0x3fc9c293 */
  { 846,   0}, /* [105] desc@0x3fc9c299 */
  { 842,   0}, /* [106] desc@0x3fc9c29f */
  { 841,   0}, /* [107] desc@0x3fc9c2a5 */
  { 824,   0}, /* [108] desc@0x3fc9c2ab */
  { 815,   0}, /* [109] desc@0x3fc9c2b1 */
  { 806,   0}, /* [110] desc@0x3fc9c2b7 */
  { 797,   0}, /* [111] desc@0x3fc9c2bd */
  { 788,   0}, /* [112] desc@0x3fc9c2c3 */
  { 771,   0}, /* [113] desc@0x3fc9c2c9 */
  { 770,   0}, /* [114] desc@0x3fc9c2cf */
  { 757,   0}, /* [115] desc@0x3fc9c2d5 */
  { 735,   0}, /* [116] desc@0x3fc9c2db */
  { 733,   0}, /* [117] desc@0x3fc9c2e1 */
  { 732,   0}, /* [118] desc@0x3fc9c2e7 */
  { 715,   0}, /* [119] desc@0x3fc9c2ed */
  { 714,   0}, /* [120] desc@0x3fc9c2f3 */
  { 713,   0}, /* [121] desc@0x3fc9c2f9 */
  { 712,   0}, /* [122] desc@0x3fc9c2ff */
  { 711,   0}, /* [123] desc@0x3fc9c305 */
  { 710,   0}, /* [124] desc@0x3fc9c30b */
  { 709,   0}, /* [125] desc@0x3fc9c311 */
  { 696,   0}, /* [126] desc@0x3fc9c317 */
  { 679,   0}, /* [127] desc@0x3fc9c31d */
  { 662,   0}, /* [128] desc@0x3fc9c323 */
  { 661,   0}, /* [129] desc@0x3fc9c329 */
  { 660,   0}, /* [130] desc@0x3fc9c32f */
  { 659,   0}, /* [131] desc@0x3fc9c335 */
  { 658,   0}, /* [132] desc@0x3fc9c33b */
  { 657,   0}, /* [133] desc@0x3fc9c341 */
  { 656,   0}, /* [134] desc@0x3fc9c347 */
  { 652,   0}, /* [135] desc@0x3fc9c353 */
  { 651,   0}, /* [136] desc@0x3fc9c359 */
  { 650,   0}, /* [137] desc@0x3fc9c35f */
  { 649,   0}, /* [138] desc@0x3fc9c365 */
  { 648,   0}, /* [139] desc@0x3fc9c36b */
  { 647,   0}, /* [140] desc@0x3fc9c371 */
  { 643,   0}, /* [141] desc@0x3fc9c377 */
  { 626,   0}, /* [142] desc@0x3fc9c37d */
  { 609,   0}, /* [143] desc@0x3fc9c383 */
  { 592,   0}, /* [144] desc@0x3fc9c389 */
  { 577,   0}, /* [145] desc@0x3fc9c38f */
  { 575,   0}, /* [146] desc@0x3fc9c395 */
  { 574,   0}, /* [147] desc@0x3fc9c39b */
  { 552,   0}, /* [148] desc@0x3fc9c3a1 */
  { 450,   0}, /* [149] desc@0x3fc9c3a7 */
  { 416,   0}, /* [150] desc@0x3fc9c3ad */
  { 399,   0}, /* [151] desc@0x3fc9c3b3 */
  { 382,   0}, /* [152] desc@0x3fc9c3b9 */
  { 365,   0}, /* [153] desc@0x3fc9c3bf */
  { 348,   0}, /* [154] desc@0x3fc9c3c5 */
  { 280,   0}, /* [155] desc@0x3fc9c3d1 */
  { 263,   0}, /* [156] desc@0x3fc9c3d7 */
  { 246,   0}, /* [157] desc@0x3fc9c3dd */
  { 226,   0}, /* [158] desc@0x3fc9c3e3 */
  { 225,   0}, /* [159] desc@0x3fc9c3e9 */
  { 207,   0}, /* [160] desc@0x3fc9c3ef */
  { 206,   0}, /* [161] desc@0x3fc9c3f5 */
  { 205,   0}, /* [162] desc@0x3fc9c3fb */
  { 184,   0}, /* [163] desc@0x3fc9c401 */
  { 183,   0}, /* [164] desc@0x3fc9c407 */
  { 171,   0}, /* [165] desc@0x3fc9c40d */
  { 170,   0}, /* [166] desc@0x3fc9c413 */
  { 160,   0}, /* [167] desc@0x3fc9c419 */
  { 131,   0}, /* [168] desc@0x3fc9c41f */
  { 103,   0}, /* [169] desc@0x3fc9c42b */
  {  90,   0}, /* [170] desc@0x3fc9c437 */
  {  77,   0}, /* [171] desc@0x3fc9c43d */
  {  64,   0}, /* [172] desc@0x3fc9c449 */
  {  51,   0}, /* [173] desc@0x3fc9c44f */
  {  25,   0}, /* [174] desc@0x3fc9c455 */
  {  24,   0}, /* [175] desc@0x3fc9c45b */
  {  23,   0}, /* [176] desc@0x3fc9c461 */
  {  18,   0}, /* [177] desc@0x3fc9c467 */
  {  11,   0}, /* [178] desc@0x3fc9c46d */
  {   7,   0}, /* [179] desc@0x3fc9c473 */
  {   0,   0}, /* [180] desc@0x3fc9c479 */
};

/* elements: EL_<stock address> = index. flags0 bit1 = visible, bit0 = dirty. */
enum {
  EL_3fc9af18 = 0,
  EL_3fc9af30 = 1,
  EL_3fc9af48 = 2,
  EL_3fc9af60 = 3,
  EL_3fc9af78 = 4,
  EL_3fc9af90 = 5,
  EL_3fc9afa8 = 6,
  EL_3fc9afc0 = 7,
  EL_3fc9afd8 = 8,
  EL_3fc9aff0 = 9,
  EL_3fc9b008 = 10,
  EL_3fc9b020 = 11,
  EL_3fc9b038 = 12,
  EL_3fc9b050 = 13,
  EL_3fc9b068 = 14,
  EL_3fc9b080 = 15,
  EL_3fc9b098 = 16,
  EL_3fc9b0b0 = 17,
  EL_3fc9b0c8 = 18,
  EL_3fc9b0e0 = 19,
  EL_3fc9b0f8 = 20,
  EL_3fc9b110 = 21,
  EL_3fc9b128 = 22,
  EL_3fc9b140 = 23,
  EL_3fc9b158 = 24,
  EL_3fc9b170 = 25,
  EL_3fc9b188 = 26,
  EL_3fc9b1a0 = 27,
  EL_3fc9b1b8 = 28,
  EL_3fc9b1d0 = 29,
  EL_3fc9b1e8 = 30,
  EL_3fc9b200 = 31,
  EL_3fc9b218 = 32,
  EL_3fc9b230 = 33,
  EL_3fc9b248 = 34,
  EL_3fc9b260 = 35,
  EL_3fc9b278 = 36,
  EL_3fc9b290 = 37,
  EL_3fc9b2a8 = 38,
  EL_3fc9b2c0 = 39,
  EL_3fc9b2d8 = 40,
  EL_3fc9b2f0 = 41,
  EL_3fc9b308 = 42,
  EL_3fc9b320 = 43,
  EL_3fc9b338 = 44,
  EL_3fc9b350 = 45,
  EL_3fc9b368 = 46,
  EL_3fc9b394 = 47,
  EL_3fc9b3ac = 48,
  EL_3fc9b3c4 = 49,
  EL_3fc9b3dc = 50,
  EL_3fc9b3f4 = 51,
  EL_3fc9b40c = 52,
  EL_3fc9b424 = 53,
  EL_3fc9b43c = 54,
  EL_3fc9b454 = 55,
  EL_3fc9b46c = 56,
  EL_3fc9b484 = 57,
  EL_3fc9b49c = 58,
  EL_3fc9b4b4 = 59,
  EL_3fc9b4cc = 60,
  EL_3fc9b4e4 = 61,
  EL_3fc9b4fc = 62,
  EL_3fc9b514 = 63,
  EL_3fc9b52c = 64,
  EL_3fc9b544 = 65,
  EL_3fc9b55c = 66,
  EL_3fc9b574 = 67,
  EL_3fc9b58c = 68,
  EL_3fc9b5a4 = 69,
  EL_3fc9b5bc = 70,
  EL_3fc9b5d4 = 71,
  EL_3fc9b5ec = 72,
  EL_3fc9b604 = 73,
  EL_3fc9b61c = 74,
  EL_3fc9b634 = 75,
  EL_3fc9b64c = 76,
  EL_3fc9b664 = 77,
  EL_3fc9b67c = 78,
  EL_3fc9b694 = 79,
  EL_3fc9b6ac = 80,
  EL_3fc9b6c4 = 81,
  EL_3fc9b6dc = 82,
  EL_3fc9b6f4 = 83,
  EL_3fc9b70c = 84,
  EL_3fc9b724 = 85,
  EL_3fc9b73c = 86,
  EL_3fc9b754 = 87,
  EL_3fc9b76c = 88,
  EL_3fc9b784 = 89,
  EL_3fc9b79c = 90,
  EL_3fc9b7b4 = 91,
  EL_3fc9b7cc = 92,
  EL_3fc9b7e4 = 93,
  EL_3fc9b7fc = 94,
  EL_3fc9b814 = 95,
  EL_3fc9b82c = 96,
  EL_3fc9b844 = 97,
  EL_3fc9b85c = 98,
  EL_3fc9b874 = 99,
  EL_3fc9b88c = 100,
  EL_3fc9b8a4 = 101,
  EL_3fc9b8bc = 102,
  EL_3fc9b8d4 = 103,
  EL_3fc9b8ec = 104,
  EL_3fc9b904 = 105,
  EL_3fc9b91c = 106,
  EL_3fc9b934 = 107,
  EL_3fc9b94c = 108,
  EL_3fc9b964 = 109,
  EL_3fc9b97c = 110,
  EL_3fc9b994 = 111,
  EL_3fc9b9ac = 112,
  EL_3fc9b9c4 = 113,
  EL_3fc9b9dc = 114,
  EL_3fc9b9f4 = 115,
  EL_3fc9ba0c = 116,
  EL_3fc9ba24 = 117,
  EL_3fc9ba3c = 118,
  EL_3fc9ba54 = 119,
  EL_3fc9ba6c = 120,
  EL_3fc9ba84 = 121,
  EL_3fc9ba9c = 122,
  EL_3fc9bab4 = 123,
  EL_3fc9bacc = 124,
  EL_3fc9bae4 = 125,
  EL_3fc9bafc = 126,
  EL_3fc9bb14 = 127,
  EL_3fc9bb2c = 128,
  EL_3fc9bb44 = 129,
  EL_3fc9bb5c = 130,
  EL_3fc9bb74 = 131,
  EL_3fc9bb8c = 132,
  EL_3fc9bba4 = 133,
  EL_3fc9bbbc = 134,
  EL_3fc9bbd4 = 135,
  EL_3fc9bbec = 136,
  EL_3fc9bc04 = 137,
  EL_3fc9bc1c = 138,
  EL_3fc9bc34 = 139,
  EL_3fc9bc4c = 140,
  EL_3fc9bc64 = 141,
  EL_3fc9bc7c = 142,
  EL_3fc9bc94 = 143,
  EL_3fc9bcac = 144,
  EL_3fc9bcc4 = 145,
  EL_3fc9bcdc = 146,
  EL_3fc9bcf4 = 147,
  EL_3fc9bd0c = 148,
  EL_3fc9bd24 = 149,
  EL_3fc9bd3c = 150,
  EL_3fc9bd54 = 151,
  EL_3fc9bd6c = 152,
  EL_3fc9bd84 = 153,
  EL_3fc9bd9c = 154,
  EL_3fc9bdb4 = 155,
  EL_3fc9bdcc = 156,
  EL_3fc9bde4 = 157,
  EL_3fc9bdfc = 158,
  EL_3fc9be14 = 159,
  EL_3fc9be2c = 160,
  EL_3fc9be44 = 161,
  EL_3fc9be5c = 162,
  EL_3fc9be74 = 163,
  EL_3fc9be8c = 164,
  EL_3fc9bea4 = 165,
  EL_3fc9bebc = 166,
  EL_3fc9bed4 = 167,
  EL_3fc9beec = 168,
  EL_3fc9bf04 = 169,
  EL_3fc9bf1c = 170,
  EL_3fc9bf34 = 171,
  EL_3fc9bf4c = 172,
  EL_3fc9bf64 = 173,
  EL_3fc9bf7c = 174,
  EL_3fc9bf94 = 175,
  EL_3fc9bfac = 176,
  EL_3fc9bfc4 = 177,
  EL_3fc9bfdc = 178,
  EL_3fc9bff4 = 179,
  EL_3fc9c00c = 180,
  STOCK_ELEM_COUNT = 181
};
typedef struct { uint8_t x, y, w, h; uint8_t desc; uint8_t flags0; } stock_elem_t;
static const stock_elem_t STOCK_ELEMS[STOCK_ELEM_COUNT] = {
  {  0,  0, 80,160,  76, 0x03}, /* [  0] elem@0x3fc9af18 #998 var 0 */
  {  0, 40, 80, 80,   0, 0x03}, /* [  1] elem@0x3fc9af30 #850 var 0 */
  { 21, 45, 38, 38,   1, 0x03}, /* [  2] elem@0x3fc9af48 #225 var 0 */
  {  0, 10, 80,150,  92, 0x03}, /* [  3] elem@0x3fc9af60 #888 var 0 */
  {  0,  0, 80, 44,  77, 0x03}, /* [  4] elem@0x3fc9af78 #949 var 0 */
  {  0,  0, 80, 44,  78, 0x03}, /* [  5] elem@0x3fc9af90 #947 var 0 */
  {  0,  0, 80, 44,  79, 0x03}, /* [  6] elem@0x3fc9afa8 #945 var 0 */
  {  0,  0, 80, 44,  80, 0x03}, /* [  7] elem@0x3fc9afc0 #943 var 0 */
  {  0,  0, 80, 44,  81, 0x03}, /* [  8] elem@0x3fc9afd8 #941 var 0 */
  {  0,  0, 80, 44,  82, 0x03}, /* [  9] elem@0x3fc9aff0 #939 var 0 */
  {  0,  0, 80, 44,  83, 0x03}, /* [ 10] elem@0x3fc9b008 #937 var 0 */
  {  0,  0, 80, 44,  84, 0x03}, /* [ 11] elem@0x3fc9b020 #935 var 0 */
  {  0,  0, 80, 44,  85, 0x03}, /* [ 12] elem@0x3fc9b038 #933 var 0 */
  {  0,  0, 80, 44,  86, 0x03}, /* [ 13] elem@0x3fc9b050 #931 var 0 */
  {  0,  0, 80, 44,  87, 0x03}, /* [ 14] elem@0x3fc9b068 #929 var 0 */
  {  0,  0, 80, 44,  88, 0x03}, /* [ 15] elem@0x3fc9b080 #927 var 0 */
  {  0, 20, 80, 88,  89, 0x03}, /* [ 16] elem@0x3fc9b098 #926 var 0 */
  {  0, 78, 80, 82,  91, 0x03}, /* [ 17] elem@0x3fc9b0b0 #908 var 0 */
  {  0,  0, 80, 78,  90, 0x03}, /* [ 18] elem@0x3fc9b0c8 #909 var 0 */
  {  0,119, 80, 20, 103, 0x03}, /* [ 19] elem@0x3fc9b0e0 #848 var 0 */
  {  0,119,  7, 24,   2, 0x03}, /* [ 20] elem@0x3fc9b0f8 #843 var 0 */
  {  0,119,  7, 24,   3, 0x03}, /* [ 21] elem@0x3fc9b110 #843 var 0 */
  {  0,119,  9, 24,   4, 0x03}, /* [ 22] elem@0x3fc9b128 #843 var 0 */
  {  0,119,  9, 24,   5, 0x03}, /* [ 23] elem@0x3fc9b140 #843 var 0 */
  {  0,119,  9, 24,   6, 0x03}, /* [ 24] elem@0x3fc9b158 #843 var 0 */
  {  0,119,  9, 24,   7, 0x03}, /* [ 25] elem@0x3fc9b170 #843 var 0 */
  {  0,119,  9, 24,   8, 0x03}, /* [ 26] elem@0x3fc9b188 #843 var 0 */
  {  0,119, 12, 24,   9, 0x03}, /* [ 27] elem@0x3fc9b1a0 #843 var 0 */
  {  0,119, 12, 24,  10, 0x03}, /* [ 28] elem@0x3fc9b1b8 #843 var 0 */
  {  0,119, 12, 24,  11, 0x03}, /* [ 29] elem@0x3fc9b1d0 #843 var 0 */
  {  0,119, 12, 24,  12, 0x03}, /* [ 30] elem@0x3fc9b1e8 #843 var 0 */
  {  0, 39, 80, 80,  94, 0x03}, /* [ 31] elem@0x3fc9b200 #862 var 0 */
  {  0, 39, 80, 80,  95, 0x03}, /* [ 32] elem@0x3fc9b218 #861 var 0 */
  {  0, 39, 80, 80,  96, 0x03}, /* [ 33] elem@0x3fc9b230 #860 var 0 */
  {  0, 39, 80, 80,  97, 0x03}, /* [ 34] elem@0x3fc9b248 #859 var 0 */
  {  0, 39, 80, 80,  98, 0x03}, /* [ 35] elem@0x3fc9b260 #858 var 0 */
  {  0, 39, 80, 80,  99, 0x03}, /* [ 36] elem@0x3fc9b278 #857 var 0 */
  {  0, 39, 80, 80, 100, 0x03}, /* [ 37] elem@0x3fc9b290 #856 var 0 */
  {  0, 39, 80, 80, 101, 0x03}, /* [ 38] elem@0x3fc9b2a8 #850 var 0 */
  {  0, 39, 80, 80, 102, 0x03}, /* [ 39] elem@0x3fc9b2c0 #849 var 0 */
  {  0, 27, 80, 20, 104, 0x03}, /* [ 40] elem@0x3fc9b2d8 #847 var 0 */
  {  0, 27, 80, 20, 105, 0x03}, /* [ 41] elem@0x3fc9b2f0 #846 var 0 */
  {  0,  0, 12, 24,  13, 0x03}, /* [ 42] elem@0x3fc9b308 #843 var 0 */
  {  0,  0, 12, 24,  14, 0x03}, /* [ 43] elem@0x3fc9b320 #843 var 0 */
  {  0,  0,  5, 24,  15, 0x03}, /* [ 44] elem@0x3fc9b338 #843 var 0 */
  {  0,  0, 12, 24,  16, 0x03}, /* [ 45] elem@0x3fc9b350 #843 var 0 */
  {  0,  0, 12, 24,  17, 0x03}, /* [ 46] elem@0x3fc9b368 #843 var 0 */
  {  0,  0, 80,160, 120, 0x03}, /* [ 47] elem@0x3fc9b394 #714 var 0 */
  {  0,  0, 80,160, 121, 0x03}, /* [ 48] elem@0x3fc9b3ac #713 var 0 */
  {  0,  0, 80,160, 122, 0x03}, /* [ 49] elem@0x3fc9b3c4 #712 var 0 */
  {  0, 70, 80, 30, 123, 0x03}, /* [ 50] elem@0x3fc9b3dc #711 var 0 */
  {  0, 70, 80, 30, 130, 0x03}, /* [ 51] elem@0x3fc9b3f4 #660 var 0 */
  {  0, 70, 80, 30, 132, 0x03}, /* [ 52] elem@0x3fc9b40c #658 var 0 */
  {  0, 63, 80, 16, 133, 0x03}, /* [ 53] elem@0x3fc9b424 #657 var 0 */
  {  0, 63, 80, 34, 134, 0x03}, /* [ 54] elem@0x3fc9b43c #656 var 0 */
  {  0, 63, 80, 33, 138, 0x03}, /* [ 55] elem@0x3fc9b454 #649 var 0 */
  {  0, 70, 80, 15, 135, 0x03}, /* [ 56] elem@0x3fc9b46c #652 var 0 */
  {  0, 70, 80, 17, 136, 0x03}, /* [ 57] elem@0x3fc9b484 #651 var 0 */
  {  0, 70, 80, 18, 137, 0x03}, /* [ 58] elem@0x3fc9b49c #650 var 0 */
  { 37,107, 32, 16,  48, 0x03}, /* [ 59] elem@0x3fc9b4b4 #654 var 0 */
  { 37, 87, 32, 16,  49, 0x03}, /* [ 60] elem@0x3fc9b4cc #654 var 0 */
  { 37, 69, 32, 16,  50, 0x03}, /* [ 61] elem@0x3fc9b4e4 #654 var 0 */
  { 37, 47, 32, 16,  51, 0x03}, /* [ 62] elem@0x3fc9b4fc #654 var 0 */
  { 37,107, 32, 18,  52, 0x03}, /* [ 63] elem@0x3fc9b514 #653 var 0 */
  { 37, 87, 32, 18,  53, 0x03}, /* [ 64] elem@0x3fc9b52c #653 var 0 */
  { 37, 69, 32, 18,  54, 0x03}, /* [ 65] elem@0x3fc9b544 #653 var 0 */
  { 37, 47, 32, 18,  55, 0x03}, /* [ 66] elem@0x3fc9b55c #653 var 0 */
  {  0, 40, 80, 80, 139, 0x03}, /* [ 67] elem@0x3fc9b574 #648 var 0 */
  {  0, 40, 80, 15, 140, 0x03}, /* [ 68] elem@0x3fc9b58c #647 var 0 */
  { 58,108,  8, 18,  34, 0x03}, /* [ 69] elem@0x3fc9b5a4 #697 var 0 */
  { 54,108,  4, 18,  38, 0x03}, /* [ 70] elem@0x3fc9b5bc #707 var 0 */
  { 46,108,  8, 18,  35, 0x03}, /* [ 71] elem@0x3fc9b5d4 #697 var 0 */
  { 42,108,  4, 18,  39, 0x03}, /* [ 72] elem@0x3fc9b5ec #707 var 0 */
  { 34,108,  8, 18,  36, 0x03}, /* [ 73] elem@0x3fc9b604 #697 var 0 */
  { 30,108,  4, 18,  40, 0x03}, /* [ 74] elem@0x3fc9b61c #707 var 0 */
  { 22,108,  8, 18,  37, 0x03}, /* [ 75] elem@0x3fc9b634 #697 var 0 */
  { 14,108,  8, 18,  33, 0x03}, /* [ 76] elem@0x3fc9b64c #696 var 0 */
  {  0,  0, 80,160, 141, 0x03}, /* [ 77] elem@0x3fc9b664 #643 var 0 */
  {  0, 95, 80, 64, 127, 0x03}, /* [ 78] elem@0x3fc9b67c #679 var 0 */
  { 58, 70,  8, 18,  44, 0x03}, /* [ 79] elem@0x3fc9b694 #697 var 0 */
  { 54, 70,  4, 18,  41, 0x03}, /* [ 80] elem@0x3fc9b6ac #707 var 0 */
  { 46, 70,  8, 18,  45, 0x03}, /* [ 81] elem@0x3fc9b6c4 #697 var 0 */
  { 42, 70,  4, 18,  42, 0x03}, /* [ 82] elem@0x3fc9b6dc #707 var 0 */
  { 34, 70,  8, 18,  46, 0x03}, /* [ 83] elem@0x3fc9b6f4 #697 var 0 */
  { 30, 70,  4, 18,  43, 0x03}, /* [ 84] elem@0x3fc9b70c #707 var 0 */
  { 22, 70,  8, 18,  47, 0x03}, /* [ 85] elem@0x3fc9b724 #697 var 0 */
  { 14, 70,  8, 18, 126, 0x03}, /* [ 86] elem@0x3fc9b73c #696 var 0 */
  {  0, 48, 80, 22, 128, 0x03}, /* [ 87] elem@0x3fc9b754 #662 var 0 */
  {  0,  0, 80, 48, 129, 0x03}, /* [ 88] elem@0x3fc9b76c #661 var 0 */
  { 20, 41, 40, 77, 179, 0x03}, /* [ 89] elem@0x3fc9b784 #7 var 0 */
  { 22,110, 36, 39, 160, 0x03}, /* [ 90] elem@0x3fc9b79c #207 var 0 */
  { 40,115, 14, 24,  56, 0x03}, /* [ 91] elem@0x3fc9b7b4 #195 var 0 */
  { 26,115, 14, 24,  57, 0x03}, /* [ 92] elem@0x3fc9b7cc #195 var 0 */
  { 22,110, 36, 39, 161, 0x03}, /* [ 93] elem@0x3fc9b7e4 #206 var 0 */
  { 22,110, 36, 39, 162, 0x03}, /* [ 94] elem@0x3fc9b7fc #205 var 0 */
  { 39,115, 14, 24,  58, 0x03}, /* [ 95] elem@0x3fc9b814 #185 var 0 */
  { 26,115, 14, 24,  59, 0x03}, /* [ 96] elem@0x3fc9b82c #185 var 0 */
  {  0,  0, 80, 10, 148, 0x03}, /* [ 97] elem@0x3fc9b844 #552 var 0 */
  {  0,107, 80, 54, 149, 0x03}, /* [ 98] elem@0x3fc9b85c #450 var 0 */
  { 12, 21, 14, 24,  69, 0x03}, /* [ 99] elem@0x3fc9b874 #173 var 0 */
  { 12, 21, 14, 24,  70, 0x03}, /* [100] elem@0x3fc9b88c #173 var 0 */
  { 29, 20, 14, 24, 146, 0x03}, /* [101] elem@0x3fc9b8a4 #575 var 0 */
  { 12, 21, 14, 24,  71, 0x03}, /* [102] elem@0x3fc9b8bc #173 var 0 */
  { 12, 21, 14, 24,  72, 0x03}, /* [103] elem@0x3fc9b8d4 #173 var 0 */
  {  0,  0, 80,160, 178, 0x03}, /* [104] elem@0x3fc9b8ec #11 var 0 */
  {  0,120, 80, 54, 150, 0x03}, /* [105] elem@0x3fc9b904 #416 var 0 */
  {  0,  0, 80,130, 177, 0x03}, /* [106] elem@0x3fc9b91c #18 var 0 */
  { 21, 36, 38, 38, 159, 0x03}, /* [107] elem@0x3fc9b934 #225 var 0 */
  { 40, 52, 40, 52, 112, 0x03}, /* [108] elem@0x3fc9b94c #788 var 0 */
  {  0, 52, 40, 52, 109, 0x03}, /* [109] elem@0x3fc9b964 #815 var 0 */
  { 40,  0, 40, 52, 110, 0x03}, /* [110] elem@0x3fc9b97c #806 var 0 */
  {  0,  0, 40, 52, 111, 0x03}, /* [111] elem@0x3fc9b994 #797 var 0 */
  { 58,120, 13, 25, 163, 0x03}, /* [112] elem@0x3fc9b9ac #184 var 0 */
  { 44,120, 14, 24,  73, 0x03}, /* [113] elem@0x3fc9b9c4 #173 var 0 */
  { 30,120, 14, 24,  74, 0x03}, /* [114] elem@0x3fc9b9dc #173 var 0 */
  { 22,120,  8, 25, 164, 0x03}, /* [115] elem@0x3fc9b9f4 #183 var 0 */
  {  8,120, 14, 24,  75, 0x03}, /* [116] elem@0x3fc9ba0c #173 var 0 */
  {  0,  0, 80,160, 145, 0x03}, /* [117] elem@0x3fc9ba24 #577 var 0 */
  {  0, 10, 80,133,  93, 0x03}, /* [118] elem@0x3fc9ba3c #874 var 0 */
  { 66,116,  9, 12,  23, 0x03}, /* [119] elem@0x3fc9ba54 #129 var 0 */
  { 56,116,  8, 12,  26, 0x03}, /* [120] elem@0x3fc9ba6c #118 var 0 */
  { 28,116,  9, 12,  24, 0x03}, /* [121] elem@0x3fc9ba84 #129 var 0 */
  { 20,116,  8, 12,  27, 0x03}, /* [122] elem@0x3fc9ba9c #118 var 0 */
  { 10,116,  8, 12,  28, 0x03}, /* [123] elem@0x3fc9bab4 #118 var 0 */
  {  0,116,  8, 12,  29, 0x03}, /* [124] elem@0x3fc9bacc #118 var 0 */
  { 57, 55,  9, 12,  25, 0x03}, /* [125] elem@0x3fc9bae4 #129 var 0 */
  { 47, 55,  8, 12,  30, 0x03}, /* [126] elem@0x3fc9bafc #118 var 0 */
  { 37, 55,  8, 12,  31, 0x03}, /* [127] elem@0x3fc9bb14 #118 var 0 */
  { 24, 55,  8, 12,  32, 0x03}, /* [128] elem@0x3fc9bb2c #118 var 0 */
  { 32, 55,  5, 12, 168, 0x03}, /* [129] elem@0x3fc9bb44 #131 var 0 */
  {  0, 81, 80, 80, 108, 0x03}, /* [130] elem@0x3fc9bb5c #824 var 0 */
  {  0,  0, 80, 80, 107, 0x03}, /* [131] elem@0x3fc9bb74 #841 var 0 */
  {  0, 93, 80, 54, 157, 0x03}, /* [132] elem@0x3fc9bb8c #246 var 0 */
  {  0,  0, 80, 92, 166, 0x03}, /* [133] elem@0x3fc9bba4 #170 var 0 */
  {  0, 93, 80, 54, 156, 0x03}, /* [134] elem@0x3fc9bbbc #263 var 0 */
  {  0,  0, 80, 92, 165, 0x03}, /* [135] elem@0x3fc9bbd4 #171 var 0 */
  {  0, 93, 80, 54, 155, 0x03}, /* [136] elem@0x3fc9bbec #280 var 0 */
  {  0,  0, 80, 92, 167, 0x03}, /* [137] elem@0x3fc9bc04 #160 var 0 */
  { 42, 10, 14, 24,  60, 0x03}, /* [138] elem@0x3fc9bc1c #172 var 0 */
  { 28, 10, 14, 24,  61, 0x03}, /* [139] elem@0x3fc9bc34 #173 var 0 */
  { 47, 10, 14, 24,  62, 0x03}, /* [140] elem@0x3fc9bc4c #172 var 0 */
  { 33, 10, 14, 24,  63, 0x03}, /* [141] elem@0x3fc9bc64 #173 var 0 */
  { 19, 10, 14, 24,  64, 0x03}, /* [142] elem@0x3fc9bc7c #173 var 0 */
  { 54, 10, 14, 24,  65, 0x03}, /* [143] elem@0x3fc9bc94 #172 var 0 */
  { 40, 10, 14, 24,  66, 0x03}, /* [144] elem@0x3fc9bcac #173 var 0 */
  { 26, 10, 14, 24,  67, 0x03}, /* [145] elem@0x3fc9bcc4 #173 var 0 */
  { 12, 10, 14, 24,  68, 0x03}, /* [146] elem@0x3fc9bcdc #173 var 0 */
  {  0,111, 79, 36, 116, 0x03}, /* [147] elem@0x3fc9bcf4 #735 var 0 */
  { 20, 34, 40, 77, 180, 0x03}, /* [148] elem@0x3fc9bd0c #0 var 0 */
  {  0, 93, 80, 54, 119, 0x03}, /* [149] elem@0x3fc9bd24 #715 var 0 */
  {  0,  0, 80,103, 169, 0x03}, /* [150] elem@0x3fc9bd3c #103 var 0 */
  {  0, 93, 80, 54, 142, 0x03}, /* [151] elem@0x3fc9bd54 #626 var 0 */
  {  0, 93, 80, 54, 143, 0x03}, /* [152] elem@0x3fc9bd6c #609 var 0 */
  {  0, 93, 80, 54, 144, 0x03}, /* [153] elem@0x3fc9bd84 #592 var 0 */
  {  0, 93, 80, 54, 151, 0x03}, /* [154] elem@0x3fc9bd9c #399 var 0 */
  {  0,  0, 80,102, 170, 0x03}, /* [155] elem@0x3fc9bdb4 #90 var 0 */
  {  0, 93, 80, 54, 152, 0x03}, /* [156] elem@0x3fc9bdcc #382 var 0 */
  {  0,  0, 80,103, 171, 0x03}, /* [157] elem@0x3fc9bde4 #77 var 0 */
  {  0, 93, 80, 54, 153, 0x03}, /* [158] elem@0x3fc9bdfc #365 var 0 */
  {  0,  0, 80,103, 172, 0x03}, /* [159] elem@0x3fc9be14 #64 var 0 */
  {  0, 93, 80, 54, 154, 0x03}, /* [160] elem@0x3fc9be2c #348 var 0 */
  {  0,  0, 80,103, 173, 0x03}, /* [161] elem@0x3fc9be44 #51 var 0 */
  {  0,149, 80, 10, 147, 0x03}, /* [162] elem@0x3fc9be5c #574 var 0 */
  {  0, 93, 80, 54, 113, 0x03}, /* [163] elem@0x3fc9be74 #771 var 0 */
  {  0,  0, 80,103, 114, 0x03}, /* [164] elem@0x3fc9be8c #770 var 0 */
  { 28,  0, 22, 22, 125, 0x03}, /* [165] elem@0x3fc9bea4 #709 var 0 */
  { 28,  0, 22, 22, 117, 0x03}, /* [166] elem@0x3fc9bebc #733 var 0 */
  { 28,  0, 22, 22, 118, 0x03}, /* [167] elem@0x3fc9bed4 #732 var 0 */
  {  0,  0, 80,159, 174, 0x03}, /* [168] elem@0x3fc9beec #25 var 0 */
  {  0,  0, 80,159, 175, 0x03}, /* [169] elem@0x3fc9bf04 #24 var 0 */
  {  0, 50, 80, 40, 124, 0x03}, /* [170] elem@0x3fc9bf1c #710 var 0 */
  {  0,  0, 80,160, 176, 0x03}, /* [171] elem@0x3fc9bf34 #23 var 0 */
  { 44, 33, 14, 24,  18, 0x03}, /* [172] elem@0x3fc9bf4c #173 var 0 */
  { 30, 33, 14, 24,  19, 0x03}, /* [173] elem@0x3fc9bf64 #173 var 0 */
  { 58, 10, 14, 24,  20, 0x03}, /* [174] elem@0x3fc9bf7c #172 var 0 */
  { 44, 10, 14, 24,  21, 0x03}, /* [175] elem@0x3fc9bf94 #173 var 0 */
  { 30, 10, 14, 24,  22, 0x03}, /* [176] elem@0x3fc9bfac #173 var 0 */
  {  0, 10, 80, 45, 115, 0x03}, /* [177] elem@0x3fc9bfc4 #757 var 0 */
  {  0,128, 80, 30, 131, 0x03}, /* [178] elem@0x3fc9bfdc #659 var 0 */
  {  0,  0, 80,160, 158, 0x03}, /* [179] elem@0x3fc9bff4 #226 var 0 */
  { 28,  0, 22, 22, 106, 0x03}, /* [180] elem@0x3fc9c00c #842 var 0 */
};

static const uint8_t STOCK_SCR_70[] = {179, 178, 177, 176, 175, 174, 173, 172, 0xff}; /* hdr@0x3fc9fd3c flags 0x01 */
static const uint8_t STOCK_SCR_71[] = {171, 170, 0xff}; /* hdr@0x3fc9fd18 flags 0x01 */
static const uint8_t STOCK_SCR_72[] = {169, 170, 0xff}; /* hdr@0x3fc9fcf4 flags 0x01 */
static const uint8_t STOCK_SCR_73[] = {168, 170, 0xff}; /* hdr@0x3fc9fcd0 flags 0x01 */
static const uint8_t STOCK_SCR_76[] = {164, 180, 167, 166, 165, 163, 162, 170, 0xff}; /* hdr@0x3fc9fc94 flags 0x01 */
static const uint8_t STOCK_SCR_77[] = {161, 180, 167, 166, 165, 160, 162, 170, 0xff}; /* hdr@0x3fc9fc58 flags 0x01 */
static const uint8_t STOCK_SCR_78[] = {159, 180, 167, 166, 165, 158, 162, 170, 0xff}; /* hdr@0x3fc9fc1c flags 0x01 */
static const uint8_t STOCK_SCR_79[] = {157, 180, 167, 166, 165, 156, 162, 170, 0xff}; /* hdr@0x3fc9fbe0 flags 0x01 */
static const uint8_t STOCK_SCR_80[] = {150, 180, 167, 166, 165, 149, 162, 170, 0xff}; /* hdr@0x3fc9fb20 flags 0x01 */
static const uint8_t STOCK_SCR_81[] = {155, 180, 167, 166, 165, 154, 153, 152, 151, 162, 170, 0xff}; /* hdr@0x3fc9fb98 flags 0x01 */
static const uint8_t STOCK_SCR_82[] = {117, 116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 170, 180, 0xff}; /* hdr@0x3fc9f988 flags 0x01 */
static const uint8_t STOCK_SCR_83[] = {111, 110, 109, 108, 93, 96, 95, 94, 90, 92, 91, 170, 0xff}; /* hdr@0x3fc9f8bc flags 0x01 */
static const uint8_t STOCK_SCR_84[] = {118, 170, 0xff}; /* hdr@0x3fc9f9d8 flags 0x01 */
static const uint8_t STOCK_SCR_85[] = {104, 103, 102, 101, 100, 99, 98, 0xff}; /* hdr@0x3fc9f928 flags 0x01 */
static const uint8_t STOCK_SCR_87[] = {106, 105, 180, 0xff}; /* hdr@0x3fc9f960 flags 0x01 */
static const uint8_t STOCK_SCR_88[] = {137, 136, 0xff}; /* hdr@0x3fc9fa68 flags 0x01 */
static const uint8_t STOCK_SCR_89[] = {133, 132, 0xff}; /* hdr@0x3fc9fa20 flags 0x01 */
static const uint8_t STOCK_SCR_90[] = {135, 134, 0xff}; /* hdr@0x3fc9fa44 flags 0x01 */
static const uint8_t STOCK_SCR_91[] = {131, 130, 0xff}; /* hdr@0x3fc9f9fc flags 0x01 */
static const uint8_t STOCK_SCR_92[] = {77, 76, 75, 74, 73, 72, 71, 70, 69, 170, 0xff}; /* hdr@0x3fc9f810 flags 0x01 */
static const uint8_t STOCK_SCR_93[] = {147, 148, 146, 145, 144, 143, 142, 141, 140, 139, 138, 170, 0xff}; /* hdr@0x3fc9fad4 flags 0x01 */
static const uint8_t STOCK_SCR_94[] = {89, 0xff}; /* hdr@0x3fc9f89c flags 0x01 */
static const uint8_t STOCK_SCR_95[] = {97, 0xff}; /* hdr@0x3fc9f908 flags 0x01 */
static const uint8_t STOCK_SCR_96[] = {46, 45, 44, 43, 42, 39, 38, 37, 36, 35, 34, 33, 32, 31, 41, 40, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 0xff}; /* hdr@0x3fc9f53c flags 0x01 */
static const uint8_t STOCK_SCR_97[] = {88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 0xff}; /* hdr@0x3fc9f854 flags 0x01 */
static const uint8_t STOCK_SCR_98[] = {18, 17, 0xff}; /* hdr@0x3fc9f518 flags 0x01 */
static const uint8_t STOCK_SCR_99[] = {16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 116, 115, 114, 113, 112, 0xff}; /* hdr@0x3fc9f4b4 flags 0x01 */
static const uint8_t STOCK_SCR_100[] = {16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 93, 96, 95, 94, 90, 92, 91, 3, 0xff}; /* hdr@0x3fc9f444 flags 0x01 */
static const uint8_t STOCK_SCR_101[] = {16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 116, 115, 114, 113, 112, 2, 170, 180, 0xff}; /* hdr@0x3fc9f3d4 flags 0x01 */
static const uint8_t STOCK_SCR_102[] = {16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 116, 115, 114, 113, 112, 2, 170, 180, 0xff}; /* hdr@0x3fc9f364 flags 0x01 */
static const uint8_t STOCK_SCR_103[] = {1, 0xff}; /* hdr@0x3fc9f344 flags 0x01 */
static const uint8_t STOCK_SCR_104[] = {0, 0xff}; /* hdr@0x3fc9f324 flags 0x01 */
static const uint8_t STOCK_SCR_105[] = {68, 0xff}; /* hdr@0x3fc9f7f0 flags 0x01 */
static const uint8_t STOCK_SCR_106[] = {67, 66, 65, 64, 63, 62, 61, 60, 59, 0xff}; /* hdr@0x3fc9f7b0 flags 0x01 */
static const uint8_t STOCK_SCR_107[] = {58, 0xff}; /* hdr@0x3fc9f790 flags 0x01 */
static const uint8_t STOCK_SCR_108[] = {56, 0xff}; /* hdr@0x3fc9f750 flags 0x01 */
static const uint8_t STOCK_SCR_109[] = {55, 66, 65, 62, 61, 0xff}; /* hdr@0x3fc9f720 flags 0x01 */
static const uint8_t STOCK_SCR_110[] = {55, 66, 65, 0xff}; /* hdr@0x3fc9f6f8 flags 0x01 */
static const uint8_t STOCK_SCR_111[] = {57, 0xff}; /* hdr@0x3fc9f770 flags 0x01 */
static const uint8_t STOCK_SCR_112[] = {54, 66, 65, 62, 61, 0xff}; /* hdr@0x3fc9f6c8 flags 0x01 */
static const uint8_t STOCK_SCR_113[] = {53, 66, 65, 0xff}; /* hdr@0x3fc9f6a0 flags 0x01 */
static const uint8_t STOCK_SCR_114[] = {52, 0xff}; /* hdr@0x3fc9f680 flags 0x01 */
static const uint8_t STOCK_SCR_115[] = {51, 0xff}; /* hdr@0x3fc9f660 flags 0x01 */
static const uint8_t STOCK_SCR_116[] = {50, 0xff}; /* hdr@0x3fc9f640 flags 0x01 */
static const uint8_t STOCK_SCR_117[] = {48, 177, 176, 175, 174, 173, 172, 0xff}; /* hdr@0x3fc9f5e8 flags 0x01 */
static const uint8_t STOCK_SCR_118[] = {49, 0xff}; /* hdr@0x3fc9f620 flags 0x01 */
static const uint8_t STOCK_SCR_119[] = {47, 0xff}; /* hdr@0x3fc9f5c8 flags 0x01 */
static const uint8_t STOCK_SCR_120[] = {148, 146, 145, 144, 143, 142, 141, 140, 139, 138, 170, 0xff}; /* hdr@0x3fc9fa8c flags 0x01 */
static const uint8_t STOCK_SCR_81B[] = {150, 180, 167, 166, 165, 154, 162, 170, 0xff}; /* alternate screen 81, hdr@0x3fc9fb5c */

typedef struct { uint8_t id; const uint8_t *elems; } stock_screen_t;
static const stock_screen_t STOCK_SCREENS[] = {
  {70, STOCK_SCR_70},
  {71, STOCK_SCR_71},
  {72, STOCK_SCR_72},
  {73, STOCK_SCR_73},
  {76, STOCK_SCR_76},
  {77, STOCK_SCR_77},
  {78, STOCK_SCR_78},
  {79, STOCK_SCR_79},
  {80, STOCK_SCR_80},
  {81, STOCK_SCR_81},
  {82, STOCK_SCR_82},
  {83, STOCK_SCR_83},
  {84, STOCK_SCR_84},
  {85, STOCK_SCR_85},
  {87, STOCK_SCR_87},
  {88, STOCK_SCR_88},
  {89, STOCK_SCR_89},
  {90, STOCK_SCR_90},
  {91, STOCK_SCR_91},
  {92, STOCK_SCR_92},
  {93, STOCK_SCR_93},
  {94, STOCK_SCR_94},
  {95, STOCK_SCR_95},
  {96, STOCK_SCR_96},
  {97, STOCK_SCR_97},
  {98, STOCK_SCR_98},
  {99, STOCK_SCR_99},
  {100, STOCK_SCR_100},
  {101, STOCK_SCR_101},
  {102, STOCK_SCR_102},
  {103, STOCK_SCR_103},
  {104, STOCK_SCR_104},
  {105, STOCK_SCR_105},
  {106, STOCK_SCR_106},
  {107, STOCK_SCR_107},
  {108, STOCK_SCR_108},
  {109, STOCK_SCR_109},
  {110, STOCK_SCR_110},
  {111, STOCK_SCR_111},
  {112, STOCK_SCR_112},
  {113, STOCK_SCR_113},
  {114, STOCK_SCR_114},
  {115, STOCK_SCR_115},
  {116, STOCK_SCR_116},
  {117, STOCK_SCR_117},
  {118, STOCK_SCR_118},
  {119, STOCK_SCR_119},
  {120, STOCK_SCR_120},
};
