#!/usr/bin/env python3
"""Extract the stock Oclean UI tables from the stock app image (ota.bin, blufi_demo, IDF v5.1.1).
Read-only. Usage: extract_ui_tables.py [ota.bin] > stock_ui_tables.h

All addresses below were recovered from the disassembly (see comments); nothing here is guessed:
  PIC_OFF   DROM 0x3c11b248  927 x u32  picture offsets inside the type-0x40/subtype-0x00 data partition
                             (used by 0x40378440: offset = PIC_OFF[base_id + variant])
  ZONE_OFF  DROM 0x3c11b1e8   24 x u32  frame offsets for ids 927..950, added to 0x77e000 (0x40378605 path)
  ELEMS     DRAM 0x3fc9af18..0x3fc9c01c  24-byte element structs {x,y,w,h,u32 type,desc*,u32,flags*,u8 flags}
  DESCS     DRAM 0x3fc9c023..            6-byte "*C#" descriptors {'*','C','#',hi,lo,variant}
  SCREENS   DRAM 0x3fc9f324..            16-byte headers {flags*, elem**, ?, cb} + NULL-terminated elem* array
  screen-id -> screen header mapping is the switch in 0x42020108 (recovered by symbolic execution).
"""
import struct, sys

path = sys.argv[1] if len(sys.argv) > 1 else 'ota.bin'
img = open(path, 'rb').read()
DROM_VMA, DROM_OFF = 0x3c110020, 0x20
DRAM_VMA, DRAM_OFF = 0x3fc99e00, 0x41698
def drom(v): return v - DROM_VMA + DROM_OFF
def dram(v): return v - DRAM_VMA + DRAM_OFF
def u32d(v): return struct.unpack_from('<I', img, dram(v))[0]
def u8d(v): return img[dram(v)]

PIC_OFF = list(struct.unpack_from('<927I', img, drom(0x3c11b248)))
ZONE_OFF = list(struct.unpack_from('<24I', img, drom(0x3c11b1e8)))

def desc_id(a):
    assert img[dram(a):dram(a) + 3] == b'*C#', hex(a)
    hi, lo = u8d(a + 3), u8d(a + 4)
    v = (hi << 8) | lo
    if hi in (1, 2, 3):          # 0x40378440: id -= hi when hi in 1..3
        v -= hi
    return v

# elements: scan the element region with the layout validated in 0x42023c74 / 0x42023b5c
elems = {}
a = 0x3fc9af18
while a <= 0x3fc9c00c:
    t, p8, p16 = u32d(a + 4), u32d(a + 8), u32d(a + 16)
    if t == 3 and p16 == a + 20 and img[dram(p8):dram(p8) + 3] == b'*C#':
        elems[a] = dict(x=u8d(a), y=u8d(a + 1), w=u8d(a + 2), h=u8d(a + 3), desc=p8,
                        base=desc_id(p8), var=u8d(p8 + 5), flags=u8d(a + 20))
        a += 24
    else:
        a += 4

# screen id -> screen header (from 0x42020108)
SCREEN_ID = {70: 0x3fc9fd3c, 71: 0x3fc9fd18, 72: 0x3fc9fcf4, 73: 0x3fc9fcd0, 76: 0x3fc9fc94, 77: 0x3fc9fc58,
             78: 0x3fc9fc1c, 79: 0x3fc9fbe0, 80: 0x3fc9fb20, 81: 0x3fc9fb98, 82: 0x3fc9f988, 83: 0x3fc9f8bc,
             84: 0x3fc9f9d8, 85: 0x3fc9f928, 87: 0x3fc9f960, 88: 0x3fc9fa68, 89: 0x3fc9fa20, 90: 0x3fc9fa44,
             91: 0x3fc9f9fc, 92: 0x3fc9f810, 93: 0x3fc9fad4, 94: 0x3fc9f89c, 95: 0x3fc9f908, 96: 0x3fc9f53c,
             97: 0x3fc9f854, 98: 0x3fc9f518, 99: 0x3fc9f4b4, 100: 0x3fc9f444, 101: 0x3fc9f3d4, 102: 0x3fc9f364,
             103: 0x3fc9f344, 104: 0x3fc9f324, 105: 0x3fc9f7f0, 106: 0x3fc9f7b0, 107: 0x3fc9f790, 108: 0x3fc9f750,
             109: 0x3fc9f720, 110: 0x3fc9f6f8, 111: 0x3fc9f770, 112: 0x3fc9f6c8, 113: 0x3fc9f6a0, 114: 0x3fc9f680,
             115: 0x3fc9f660, 116: 0x3fc9f640, 117: 0x3fc9f5e8, 118: 0x3fc9f620, 119: 0x3fc9f5c8, 120: 0x3fc9fa8c}
# 81 has an alternate header 0x3fc9fb5c (SCR39) when profile bytes 0x3fca4c85[0]!=1 and [2]!=1

def screen_elems(S):
    arr = u32d(S + 4)
    out = []
    while True:
        e = u32d(arr + 4 * len(out))
        if e == 0:
            return out
        out.append(e)

order = sorted(elems)
index = {e: i for i, e in enumerate(order)}
descs = sorted(set(d['desc'] for d in elems.values()))
dindex = {a: i for i, a in enumerate(descs)}
P = print
P('/* Stock Oclean X Ultra 20 UI layout tables: picture offsets, elements, descriptors and')
P(' * screen lists. Generated by re/tools/extract_ui_tables.py from the stock ota.bin.')
P(' * Layout only -- the pictures themselves stay in the brush\'s resource partition. */')
P('#pragma once\n#include <stdint.h>\n')
P('/* picture offsets in the type 0x40 / subtype 0x00 data partition (stock rodata 0x3c11b248) */')
P('#define STOCK_PIC_COUNT 927')
P('static const uint32_t STOCK_PIC_OFF[STOCK_PIC_COUNT] = {')
for i in range(0, 927, 8):
    P('  ' + ', '.join('0x%06x' % v for v in PIC_OFF[i:i + 8]) + ',')
P('};\n')
P('/* ids 927..950: offset = 0x77e000 + STOCK_ZONE_OFF[id-927]; 44 rows x 240 B (80 px x {b0,b1,alpha}) (stock rodata 0x3c11b1e8) */')
P('static const uint32_t STOCK_ZONE_OFF[24] = {' + ', '.join('0x%x' % v for v in ZONE_OFF) + '};\n')
P('/* descriptors ("*C#" + id + variant in stock RAM): the variant byte is the dynamic part.')
P(' * DS_<stock address> = index. */')
P('enum {')
for a in descs:
    P('  DS_%08x = %d,' % (a, dindex[a]))
P('  STOCK_DESC_COUNT = %d' % len(descs))
P('};')
P('typedef struct { uint16_t base_id; uint8_t var0; } stock_desc_t;')
P('static const stock_desc_t STOCK_DESCS[STOCK_DESC_COUNT] = {')
for a in descs:
    P('  {%4d, %3d}, /* [%3d] desc@0x%08x */' % (desc_id(a), u8d(a + 5), dindex[a], a))
P('};\n')
P('/* elements: EL_<stock address> = index. flags0 bit1 = visible, bit0 = dirty. */')
P('enum {')
for e in order:
    P('  EL_%08x = %d,' % (e, index[e]))
P('  STOCK_ELEM_COUNT = %d' % len(order))
P('};')
P('typedef struct { uint8_t x, y, w, h; uint8_t desc; uint8_t flags0; } stock_elem_t;')
P('static const stock_elem_t STOCK_ELEMS[STOCK_ELEM_COUNT] = {')
for e in order:
    d = elems[e]
    P('  {%3d,%3d,%3d,%3d, %3d, 0x%02x}, /* [%3d] elem@0x%08x #%d var %d */' % (
        d['x'], d['y'], d['w'], d['h'], dindex[d['desc']], d['flags'], index[e], e, d['base'], d['var']))
P('};\n')
SCR81B = 0x3fc9fb5c
allscr = dict(SCREEN_ID); 
for sid, S in sorted(allscr.items()):
    el = screen_elems(S)
    P('static const uint8_t STOCK_SCR_%d[] = {%s, 0xff}; /* hdr@0x%08x flags 0x%02x */' % (
        sid, ', '.join(str(index[e]) for e in el), S, u8d(u32d(S))))
el = screen_elems(SCR81B)
P('static const uint8_t STOCK_SCR_81B[] = {%s, 0xff}; /* alternate screen 81, hdr@0x%08x */' % (', '.join(str(index[e]) for e in el), SCR81B))
P('\ntypedef struct { uint8_t id; const uint8_t *elems; } stock_screen_t;')
P('static const stock_screen_t STOCK_SCREENS[] = {')
for sid in sorted(SCREEN_ID):
    P('  {%d, STOCK_SCR_%d},' % (sid, sid))
P('};')
sys.stderr.write('elements=%d descs=%d screens=%d last_pic_off=0x%x\n' % (len(order), len(descs), len(SCREEN_ID), PIC_OFF[-1]))
